language: python
python:
  - "3.5"
  - "3.6"
services:
  - mysql
# command to install dependencies
install:
  - virtualenv -p python3 .
  - source bin/activate
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: ./test