language: python
sudo: required
python:
  - "3.8.5"
services:
  - mysql
install:
  - pip3 install -r requirements.txt
  - pip3 install -e .
script:
  - safety check -r requirements.txt
  - safety check
  - ./test.travis
after_success:
  - codecov
