language: python
sudo: required
python:
  - "3.6"
services:
  - mysql
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: ./test.travis
after_sucess:
  - CODECLIMATE_REPO_TOKEN=b77e5f9ff68c9b8b3aa905273349ef3f440cbb69f55a1e5666775322c8463480 codeclimate-test-reporter