language: python
sudo: required
python:
  - "3.6.5"
  # - "3.7-dev"
services:
  - mysql
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - safety check -r requirements.txt
  - safety check
  - ./test.travis
after_success:
  - codecov
