language: python
sudo: required
python:
  - "3.6"
  - "3.7-dev"
services:
  - mysql
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - ./test.travis
after_success:
  - CODECLIMATE_REPO_TOKEN=b77e5f9ff68c9b8b3aa905273349ef3f440cbb69f55a1e5666775322c8463480 codeclimate-test-reporter