language: python
sudo: required
python:
  - "3.5"
  - "3.6"
services:
  - mysql
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: ./test.travis