---
version: "2.3"
services:
  mysql:
    image: "mysql:5.7.20"
    container_name: subscity-v2-db
    network_mode: "${NET:-bridge}"
    restart: always
    ports:
      - 3307:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    env_file:
      - env/${ENV:-local}
#    volumes:
#      - /var/lib/mysql-sc:/var/lib/mysql
  mysql-test:
    image: "mysql:5.7.20"
    container_name: subscity-v2-db-test
    network_mode: "${NET:-bridge}"
    restart: always
    ports:
      - 3308:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    env_file:
      - env/${ENV:-local}
#    volumes:
#      - /var/lib/mysql-sc-test:/var/lib/mysql
