#!/bin/sh
if [ -z $1 ]; then
    pyenv exec pylint --rcfile=.pylintrc subscity
    pyenv exec pycodestyle --config=pycodestyle.ini subscity
else
    pyenv exec pylint --rcfile=.pylintrc $@
    pyenv exec pycodestyle --config=pycodestyle.ini $@
fi
