name: Build, Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          - "3.9"
          # - "3.10-dev"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -e .

      - name: Safety check
        run: |
          safety check -r requirements.txt
          safety check

      - name: Shutdown Ubuntu MySQL
        run: |
          sudo service mysql stop
          sleep 5

      - name: Set up new MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_unicode_ci'
          mysql version: '8.0'
          mysql database: 'subscity'
          mysql root password: 'password'

      - name: Verify DB connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 3
            echo "Waiting for DB to start..."
          done

      - name: Run test DB query
        run: |
          mysql -h 127.0.0.1 -u root --password=password -e 'select 1;'

      - name: Run tests
        run: |
          ./test.github

      - name: Code coverage
        run: |
          codecov
